### ISSUE TITLE
Mismatch between the number of arguments

### ISSUE THREAD

**Issue by deepurajr** [e-pet/adni-bias#2]
The number of arguments passed to train_model() in 
https://github.com/e-pet/adni-bias/blob/main/Low_Dim_Models.py#L255
is 9, but the train_model() expects only 8 arguments and the code throws an error because of this mismatch. 
The 5th argument - [args.split_ver] is not needed and can be removed.

**Comment by e-pet** [comment]
Thanks! That was an old leftover from the code version I used during development. Fixed it.
